CREATE TABLE USER_SAVE(
  UUID_USER UUID ,
  USER_IDENTIFICATION varchar (10)  ,
  USER_PASSWORD varchar (30)  ,
  USER_AUTHORIZATION varchar (1)
);
CREATE TABLE CUSTOMER_SAVE(
  UUID_CUSTOMER UUID,
  CUSTOMER_GENDER VARCHAR(10),
  CUSTOMER_LASTNAME VARCHAR(50),
  CUSTOMER_FIRSTNAME VARCHAR(50),
  CUSTOMER_ADRESS1 VARCHAR(50),
  CUSTOMER_ADRESS2 VARCHAR(50),
  CUSTOMER_ZIPCODE VARCHAR(15),
  CUSTOMER_TOWN VARCHAR(50),
  CUSTOMER_COUNTRY VARCHAR(20),
  CUSTOMER_PHONE VARCHAR(10),
  CUSTOMER_MAIL VARCHAR(50),
  CUSTOMER_BIRTH_DATE DATE,
  CUSTOMER_DOCTOR VARCHAR(50),
  CUSTOMER_CODE_SECU BIGINT,
  CUSTOMER_CODE_IBAN VARCHAR(34),
  CUSTOMER_NBCHILDREN INTEGER,
  CUSTOMER_COUPLE BOOLEAN,
  CUSTOMER_CREATE_DATE DATE,
  CUSTOMER_UPDATE_DATE DATE,
  CUSTOMER_CLOSE_DATE DATE,
  CUSTOMER_ACTIVE VARCHAR(1)
);
/* sauvegarde du contenu des tables */
INSERT INTO USER_SAVE SELECT * FROM USER_TAB;
select count(*) from USER_SAVE;
select count(*) from USER_TAB;

INSERT INTO CUSTOMER_SAVE SELECT * FROM CUSTOMER;
select count(*) from CUSTOMER_SAVE;
select count(*) from CUSTOMER;

/* suppression des tables pour les créer avec la nouvelle structure */
DROP TABLE USER_TAB;
DROP TABLE CUSTOMER;

CREATE TABLE USER_TAB (
  UUID_USER UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  USER_IDENTIFICATION varchar (14)      NOT NULL,
  USER_PASSWORD varchar (14)            NOT NULL
);

CREATE TABLE CUSTOMER (
  UUID_CUSTOMER UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  CUSTOMER_GENDER VARCHAR(10) Default 'N/A',
  CUSTOMER_LASTNAME VARCHAR(20) Default 'N/A',
  CUSTOMER_FIRSTNAME VARCHAR(20) Default 'N/A',
  CUSTOMER_ADRESS1 VARCHAR(50) Default 'N/A',
  CUSTOMER_ADRESS2 VARCHAR(50) Default 'N/A',
  CUSTOMER_ZIPCODE VARCHAR(15) Default 'N/A',
  CUSTOMER_TOWN VARCHAR(30) Default 'N/A',
  CUSTOMER_COUNTRY VARCHAR(20)  Default 'N/A',
  CUSTOMER_PHONE VARCHAR(10) Default 'N/A',
  CUSTOMER_MAIL VARCHAR(50) Default 'N/A',
  CUSTOMER_BIRTH_DATE DATE Default '0001-01-01',
  CUSTOMER_DOCTOR VARCHAR(20) Default 'N/A',
  CUSTOMER_CODE_SECU BIGINT Default 0,
  CUSTOMER_CODE_IBAN VARCHAR(34) Default 'N/A',
  CUSTOMER_NBCHILDREN INTEGER Default 0,
  CUSTOMER_COUPLE BOOLEAN,
  CUSTOMER_CREATE_DATE DATE Default '0001-01-01',
  CUSTOMER_UPDATE_DATE DATE Default '0001-01-01',
  CUSTOMER_CLOSE_DATE DATE Default '0001-01-01',
  CUSTOMER_ACTIVE VARCHAR(1) Default '1'
);

/* chargement des données sauvegardées */
INSERT INTO USER_TAB (UUID_USER, USER_IDENTIFICATION, USER_PASSWORD) 
SELECT UUID_USER, USER_IDENTIFICATION, USER_PASSWORD FROM USER_SAVE;
SELECT * FROM USER_TAB;

INSERT INTO CUSTOMER SELECT * FROM CUSTOMER_SAVE;
SELECT * FROM CUSTOMER;

/* suppression des tables de sauvegarde */
DROP TABLE USER_SAVE;
DROP TABLE CUSTOMER_SAVE;