CREATE TABLE USER_SAVE(
  UUID_USER UUID,
  USER_IDENTIFICATION varchar(10),
  USER_PASSWORD varchar(30),
  USER_AUTHORIZATION varchar(1)
);

CREATE TABLE CUSTOMER_SAVE(
  UUID_CUSTOMER UUID,
  CUSTOMER_GENDER VARCHAR(10),
  CUSTOMER_LASTNAME VARCHAR(50),
  CUSTOMER_FIRSTNAME VARCHAR(50),
  CUSTOMER_ADRESS1 VARCHAR(50),
  CUSTOMER_ADRESS2 VARCHAR(50),
  CUSTOMER_ZIPCODE VARCHAR(15),
  CUSTOMER_TOWN VARCHAR(50),
  CUSTOMER_COUNTRY VARCHAR(20),
  CUSTOMER_PHONE VARCHAR(10),
  CUSTOMER_MAIL VARCHAR(50),
  CUSTOMER_BIRTH_DATE DATE,
  CUSTOMER_DOCTOR VARCHAR(50),
  CUSTOMER_CODE_SECU BIGINT,
  CUSTOMER_CODE_IBAN VARCHAR(34),
  CUSTOMER_NBCHILDREN INTEGER,
  CUSTOMER_COUPLE BOOLEAN,
  CUSTOMER_CREATE_DATE DATE,
  CUSTOMER_UPDATE_DATE DATE,
  CUSTOMER_CLOSE_DATE DATE,
  CUSTOMER_ACTIVE VARCHAR(1)
);

/* Sauvegarde du contenu des tables */
INSERT INTO USER_SAVE SELECT * FROM USER_TAB;
SELECT COUNT(*) FROM USER_SAVE;
SELECT COUNT(*) FROM USER_TAB;

INSERT INTO CUSTOMER_SAVE SELECT * FROM CUSTOMER;
SELECT COUNT(*) FROM CUSTOMER_SAVE;
SELECT COUNT(*) FROM CUSTOMER;

/* Suppression des tables pour les créer avec la nouvelle structure */
DROP TABLE USER_TAB;
DROP TABLE CUSTOMER;

/* Création de la nouvelle structure de tables */
CREATE TABLE USER_TAB (
  UUID_USER UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  USER_IDENTIFICATION VARCHAR(14) NOT NULL,
  USER_PASSWORD VARCHAR(14) NOT NULL
);

CREATE TABLE CUSTOMER (
  UUID_CUSTOMER UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  CUSTOMER_GENDER VARCHAR(10) DEFAULT 'N/A',
  CUSTOMER_LASTNAME VARCHAR(20) DEFAULT 'N/A',
  CUSTOMER_FIRSTNAME VARCHAR(20) DEFAULT 'N/A',
  CUSTOMER_ADRESS1 VARCHAR(50) DEFAULT 'N/A',
  CUSTOMER_ADRESS2 VARCHAR(50) DEFAULT 'N/A',
  CUSTOMER_ZIPCODE VARCHAR(15) DEFAULT 'N/A',
  CUSTOMER_TOWN VARCHAR(30) DEFAULT 'N/A',
  CUSTOMER_COUNTRY VARCHAR(20) DEFAULT 'N/A',
  CUSTOMER_PHONE VARCHAR(10) DEFAULT 'N/A',
  CUSTOMER_MAIL VARCHAR(50) DEFAULT 'N/A',
  CUSTOMER_BIRTH_DATE DATE DEFAULT '0001-01-01',
  CUSTOMER_DOCTOR VARCHAR(20) DEFAULT 'N/A',
  CUSTOMER_CODE_SECU BIGINT DEFAULT 0,
  CUSTOMER_CODE_IBAN VARCHAR(34) DEFAULT 'N/A',
  CUSTOMER_NBCHILDREN INTEGER DEFAULT 0,
  CUSTOMER_COUPLE BOOLEAN,
  CUSTOMER_CREATE_DATE DATE DEFAULT '0001-01-01',
  CUSTOMER_UPDATE_DATE DATE DEFAULT '0001-01-01',
  CUSTOMER_CLOSE_DATE DATE DEFAULT '0001-01-01',
  CUSTOMER_ACTIVE VARCHAR(1) DEFAULT '1'
);

CREATE TABLE CUSTOMER_ARCHIVE (
  UUID_CUSTOMER_ARCHIVE UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ARCHIVE_GENDER VARCHAR(10) DEFAULT 'N/A',
  ARCHIVE_LASTNAME VARCHAR(20) DEFAULT 'N/A',
  ARCHIVE_FIRSTNAME VARCHAR(20) DEFAULT 'N/A',
  ARCHIVE_ADRESS1 VARCHAR(50) DEFAULT 'N/A',
  ARCHIVE_ADRESS2 VARCHAR(50) DEFAULT 'N/A',
  ARCHIVE_ZIPCODE VARCHAR(15) DEFAULT 'N/A',
  ARCHIVE_TOWN VARCHAR(30) DEFAULT 'N/A',
  ARCHIVE_COUNTRY VARCHAR(20) DEFAULT 'N/A',
  ARCHIVE_PHONE VARCHAR(10) DEFAULT 'N/A',
  ARCHIVE_MAIL VARCHAR(50) DEFAULT 'N/A',
  ARCHIVE_BIRTH_DATE DATE DEFAULT '0001-01-01',
  ARCHIVE_DOCTOR VARCHAR(20) DEFAULT 'N/A',
  ARCHIVE_CODE_SECU BIGINT DEFAULT 0,
  ARCHIVE_CODE_IBAN VARCHAR(34) DEFAULT 'N/A',
  ARCHIVE_NBCHILDREN INTEGER DEFAULT 0,
  ARCHIVE_COUPLE BOOLEAN,
  ARCHIVE_CREATE_DATE DATE DEFAULT '0001-01-01',
  ARCHIVE_UPDATE_DATE DATE DEFAULT '0001-01-01',
  ARCHIVE_CLOSE_DATE DATE DEFAULT '0001-01-01',
  ARCHIVE_ACTIVE VARCHAR(1) DEFAULT '1'
);

/* Chargement des données sauvegardées */
INSERT INTO USER_TAB (UUID_USER, USER_IDENTIFICATION, USER_PASSWORD) 
SELECT UUID_USER, USER_IDENTIFICATION, USER_PASSWORD FROM USER_SAVE;
SELECT * FROM USER_TAB;

INSERT INTO CUSTOMER SELECT * FROM CUSTOMER_SAVE;
SELECT * FROM CUSTOMER;

/* Suppression des tables de sauvegarde */
DROP TABLE USER_SAVE;
DROP TABLE CUSTOMER_SAVE;
