
CREATE TABLE COST_CONDITION (
  UUID_COST_CONDITION UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  CLASSIC_REIMBURSEMENT_NUMBER integer,
  COST_CONDITION_TYPE varchar(1) Default 'Z',
  COST_CONDITION_AGEMIN integer  Default 0,
  COST_CONDITION_AGEMAX integer Default 0,
  COST_CONDITION_COUPLE boolean,
  COST_CONDITION_COST integer Default 0,
  COST_CONDITION_CREATE_DATE date Default '0001-01-01',
  COST_CONDITION_UPDATE_DATE date Default '0001-01-01',
  FOREIGN KEY (CLASSIC_REIMBURSEMENT_NUMBER) REFERENCES CLASSIC_REIMBURSEMENT (CLASSIC_REIMBURSEMENT_NUMBER)
);


/*****************************************************************************************/
/*            Table des couts                                                            */
/*****************************************************************************************/

/* Contrat Excellence + enfants */

INSERT INTO COST_CONDITION (CLASSIC_REIMBURSEMENT_NUMBER, COST_CONDITION_TYPE, COST_CONDITION_AGEMIN,
COST_CONDITION_AGEMAX, COST_CONDITION_COUPLE, COST_CONDITION_COST, 
COST_CONDITION_CREATE_DATE,COST_CONDITION_UPDATE_DATE )
VALUES 
/* condition par enfant à charge */
 ((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE'),
 '1', 0, 0, False, 10, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul - 30 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE'),
'2', 0, 30, False, 45, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul + 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE'),
'2', 65, 0, False, 50, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul entre 30 et 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE'),
'2', 30, 65, False, 40, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple - 30 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE'),
'2', 0, 30, True, 60, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple + 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE'),
'2', 65, 0, True, 65, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple entre 30 et 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE'),
'2', 30, 65, True, 60, CURRENT_DATE, '0001-01-01')
;

SELECT 'Formule EXCELLENCE', COUNT(*) FROM COST_CONDITION
WHERE CLASSIC_REIMBURSEMENT_NUMBER = 
(SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT 
        WHERE CLASSIC_REIMBURSEMENT_LABEL = 'EXCELLENCE');

/* Contrat Modéré */

INSERT INTO COST_CONDITION (CLASSIC_REIMBURSEMENT_NUMBER, COST_CONDITION_TYPE, COST_CONDITION_AGEMIN,
COST_CONDITION_AGEMAX, COST_CONDITION_COUPLE, COST_CONDITION_COST, 
COST_CONDITION_CREATE_DATE,COST_CONDITION_UPDATE_DATE )
VALUES 
/* condition par enfant à charge */
 ((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE'),
 '1', 0, 0, False, 10, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul - 30 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE'),
 '2', 0, 30, False, 35, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul + 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE'),
 '2', 65, 0, False, 35, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul entre 30 et 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE'),
'2', 30, 65, False, 30, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple - 30 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE'),
'2', 0, 30, True, 53, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple + 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE'),
'2', 65, 0, True, 60, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple entre 30 et 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE'),
'2', 30, 65, True, 50, CURRENT_DATE, '0001-01-01')
;

SELECT 'Formule MODEREE', COUNT(*) FROM COST_CONDITION
WHERE CLASSIC_REIMBURSEMENT_NUMBER = 
(SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT 
        WHERE CLASSIC_REIMBURSEMENT_LABEL = 'MODERE');

/* Contrat Allégé */

INSERT INTO COST_CONDITION (CLASSIC_REIMBURSEMENT_NUMBER, COST_CONDITION_TYPE, COST_CONDITION_AGEMIN,
COST_CONDITION_AGEMAX, COST_CONDITION_COUPLE, COST_CONDITION_COST, 
COST_CONDITION_CREATE_DATE,COST_CONDITION_UPDATE_DATE )
VALUES 
/* condition par enfant à charge */
 ((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE'),
 '1', 0, 0, False, 10, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul - 30 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE'),
 '2', 0, 30, False, 25, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul + 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE'),
 '2', 65, 0, False, 25, CURRENT_DATE, '0001-01-01'),
/* condition adhérent seul entre 30 et 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE'),
'2', 30, 65, False, 20, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple - 30 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE'),
'2', 0, 30, True, 45, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple + 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE'),
'2', 65, 0, True, 50, CURRENT_DATE, '0001-01-01'),
/* condition adhérent en couple entre 30 et 65 ans */
((SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE'),
'2', 30, 65, True, 40, CURRENT_DATE, '0001-01-01')
;

SELECT 'Formule ALLEGEE', COUNT(*) FROM COST_CONDITION 
WHERE CLASSIC_REIMBURSEMENT_NUMBER = 
(SELECT CLASSIC_REIMBURSEMENT_NUMBER FROM CLASSIC_REIMBURSEMENT 
        WHERE CLASSIC_REIMBURSEMENT_LABEL = 'ALLEGE');